[package]
name = "openai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "openai"
path = "src/lib.rs"

[dependencies]
async-openai = "0.28.0"
log = "0.4.26"
bytes = "1.10.1"
