//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::chat_record::Entity as ChatRecord;
pub use super::device_data::Entity as DeviceData;
pub use super::user_data::Entity as UserData;
