//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub imei: String,
    pub user_id: String,
    pub service_token: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::device_data::Entity")]
    DeviceData,
}

impl Related<super::device_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
